package dam.ad.jdbc.statements.prepared;

public class SQLStatements {

    public static final String SQL_CREATE_TABLE_EQUIPO = """
            CREATE TABLE equipo(
                equipoID INTEGER IDENTITY PRIMARY KEY,
                nombre VARCHAR(35) NOT NULL,
                pais CHAR(3) NOT NULL)
            """;

    public static final String SQL_CREATE_TABLE_JUGADOR = """
            CREATE TABLE jugador (
                jugadorID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
                nombre VARCHAR(30) NOT NULL,
                pais CHAR(3) NOT NULL,
                nacimiento DATE,
                estatura DECIMAL(3,2),
                peso INTEGER,
                dorsal INTEGER,
                equipoID INTEGER REFERENCES equipo)
            """;

    public static final String SQL_DELETE_ALL_EQUIPOS = """
            DELETE FROM equipo
            """;

    public static final String SQL_DELETE_ALL_JUGADORES = """
            DELETE FROM jugador
            """;

}
